{
   "songs":[
      {
         "id":"acc",
         "tunings":[
            "Ds2",
            "Gs2",
            "Ds3",
            "Gs3",
            "As3",
            "Ds4"
         ]
      },
      {
         "id":"aer",
         "tunings":[
            "D2",
            "G2",
            "D3",
            "F3",
            "A3",
            "C4"
         ]
      },
      {
         "id":"alt",
         "tunings":[
            "D2",
            "A2",
            "D3",
            "A3",
            "D4",
            "E4"
         ]
      },
      {
         "id":"asf",
         "tunings":[
            "E2",
            "A2",
            "E3",
            "A3",
            "Cs4",
            "E4"
         ]
      },
      {
         "id":"aut",
         "tunings":[
            "E2",
            "A2",
            "E3",
            "A3",
            "B3",
            "E4"
         ]
      },
      {
         "id":"big",
         "tunings":[
            "D2",
            "G2",
            "D3",
            "G3",
            "B3",
            "D4"
         ]
      },
      {
         "id":"bli",
         "tunings":[
            "Ds2",
            "As1",
            "Ds3",
            "As2",
            "Ds4",
            "F4"
         ]
      },
      {
         "id":"bor",
         "tunings":[
            "E2",
            "A2",
            "D3",
            "G3",
            "B3",
            "E4"
         ]
      },
      {
         "id":"can",
         "tunings":[
            "D2",
            "A2",
            "E3",
            "A3",
            "Cs4",
            "E4"
         ]
      },
      {
         "id":"cle",
         "tunings":[
            "Ds2",
            "Gs2",
            "Ds3",
            "Gs3",
            "C4",
            "Ds4"
         ]
      },
      {
         "id":"com",
         "tunings":[
            "E2",
            "A2",
            "E3",
            "A3",
            "Cs4",
            "E4"
         ]
      },
      {
         "id":"coo",
         "tunings":[
            "D2",
            "A2",
            "D3",
            "A3",
            "D4",
            "E4"
         ]
      },
      {
         "id":"day",
         "tunings":[
            "E2",
            "A2",
            "E3",
            "A3",
            "Cs4",
            "E4"
         ]
      },
      {
         "id":"die",
         "tunings":[
            "D2",
            "A2",
            "E3",
            "A3",
            "D4",
            "E4"
         ]
      },
      {
         "id":"din",
         "tunings":[
            "E2",
            "A2",
            "E3",
            "A3",
            "Cs4",
            "E4"
         ]
      },
      {
         "id":"dir",
         "tunings":[
            "C2",
            "G2",
            "C3",
            "F3",
            "G3",
            "C4"
         ]
      },
      {
         "id":"dus",
         "tunings":[
            "E2",
            "Gs2",
            "B2",
            "E3",
            "Gs3",
            "B3"
         ]
      },
      {
         "id":"fir",
         "tunings":[
            "D2",
            "A2",
            "D3",
            "A3",
            "D4",
            "E4"
         ]
      },
      {
         "id":"fla",
         "tunings":[
            "E2",
            "B2",
            "E3",
            "Gs3",
            "B3",
            "E4"
         ]
      },
      {
         "id":"fro",
         "tunings":[
            "Cs2",
            "Gs2",
            "Cs3",
            "Fs3",
            "Gs3",
            "Cs4"
         ]
      },
      {
         "id":"gas",
         "tunings":[
            "E2",
            "A2",
            "E3",
            "A3",
            "Cs4",
            "E4"
         ]
      },
      {
         "id":"god",
         "tunings":[
            "E2",
            "A2",
            "D3",
            "G3",
            "B3",
            "E4"
         ]
      },
      {
         "id":"gun",
         "tunings":[
            "Ds2",
            "As1",
            "Ds3",
            "As3",
            "Ds4",
            "F4"
         ]
      },
      {
         "id":"hom",
         "tunings":[
            "Ds2",
            "Gs2",
            "Ds3",
            "Gs3",
            "As3",
            "Ds4"
         ]
      },
      {
         "id":"ifo",
         "tunings":[
            "Cs2",
            "Fs1",
            "Ds3",
            "F3",
            "Gs3",
            "Cs4"
         ]
      },
      {
         "id":"imm",
         "tunings":[
            "C2",
            "G2",
            "C3",
            "G3",
            "C4",
            "D4"
         ]
      },
      {
         "id":"ind",
         "tunings":[
            "E2",
            "B2",
            "E3",
            "Gs3",
            "B3",
            "E4"
         ]
      },
      {
         "id":"kic",
         "tunings":[
            "E2",
            "A2",
            "E3",
            "A3",
            "Cs4",
            "E4"
         ]
      },
      {
         "id":"kno",
         "tunings":[
            "D2",
            "A2",
            "D3",
            "A3",
            "D4",
            "E4"
         ]
      },
      {
         "id":"lib",
         "tunings":[
            "E2",
            "B2",
            "E3",
            "Gs3",
            "B3",
            "E4"
         ]
      },
      {
         "id":"liv",
         "tunings":[
            "D2",
            "A2",
            "D3",
            "A3",
            "D4",
            "E4"
         ]
      },
      {
         "id":"loc",
         "tunings":[
            "Cs2",
            "Gs2",
            "Cs3",
            "F3",
            "Fs3",
            "Cs4"
         ]
      },
      {
         "id":"lon",
         "tunings":[
            "E2",
            "A2",
            "E3",
            "A3",
            "Cs4",
            "E4"
         ]
      },
      {
         "id":"nar",
         "tunings":[
            "D2",
            "A2",
            "E3",
            "A3",
            "Cs4",
            "E4"
         ]
      },
      {
         "id":"nev",
         "tunings":[
            "E2",
            "B2",
            "E3",
            "Gs3",
            "B3",
            "E4"
         ]
      },
      {
         "id":"new",
         "tunings":[
            "E2",
            "B2",
            "E3",
            "Gs3",
            "B3",
            "E4"
         ]
      },
      {
         "id":"ohg",
         "tunings":[
            "E2",
            "A2",
            "E3",
            "A3",
            "Cs4",
            "E4"
         ]
      },
      {
         "id":"onc",
         "tunings":[
            "D2",
            "A2",
            "D3",
            "A3",
            "D4",
            "E4"
         ]
      },
      {
         "id":"one",
         "tunings":[
            "E2",
            "A2",
            "E3",
            "A3",
            "B3",
            "E4"
         ]
      },
      {
         "id":"pho",
         "tunings":[
            "E2",
            "A2",
            "E3",
            "A3",
            "Cs4",
            "E4"
         ]
      },
      {
         "id":"poi",
         "tunings":[
            "E2",
            "B2",
            "E3",
            "Gs3",
            "B3",
            "E4"
         ]
      },
      {
         "id":"pow",
         "tunings":[
            "E2",
            "A2",
            "D3",
            "G3",
            "B3",
            "E4"
         ]
      },
      {
         "id":"scr",
         "tunings":[
            "Cs2",
            "Gs2",
            "Cs3",
            "Gs3",
            "Cs4",
            "Ds4"
         ]
      },
      {
         "id":"ser",
         "tunings":[
            "Cs2",
            "Gs2",
            "Cs3",
            "Fs3",
            "Gs3",
            "Cs4"
         ]
      },
      {
         "id":"som",
         "tunings":[
            "E2",
            "A2",
            "E3",
            "A3",
            "Cs4",
            "E4"
         ]
      },
      {
         "id":"ult",
         "tunings":[
            "E2",
            "A2",
            "E3",
            "A3",
            "Cs4",
            "E4"
         ]
      },
      {
         "id":"wei",
         "tunings":[
            "E2",
            "A2",
            "E3",
            "A3",
            "B3",
            "E4"
         ]
      },
      {
         "id":"wil",
         "tunings":[
            "D2",
            "A2",
            "D3",
            "G3",
            "A3",
            "D4"
         ]
      },
      {
         "id":"wpl",
         "tunings":[
            "D2",
            "A2",
            "D3",
            "A3",
            "D4",
            "E4"
         ]
      }
   ]
}
